import { Pool, types as pgTypes, type PoolClient, type PoolConfig } from "pg";
import * as crypto from "crypto";
import { encrypt, decrypt } from "../crypto";
import type { MaimaiProfile } from "../scraper";
import type * as Db from "./types";
import { calcSongRating, getConstant, levelToNumber } from "../constants";

pgTypes.setTypeParser(20, (value) => Number(value));

export const MIGRATION_VERSION = 16;

// Migration text is deliberately kept as separate, immutable units.  In particular,
// an edit to the current schema must not silently change an old migration checksum.
const MIGRATIONS: readonly [number, string][] = [
  [1, `CREATE TABLE IF NOT EXISTS profiles (friend_code text PRIMARY KEY, player_name text NOT NULL, rating integer DEFAULT 0, rating_max integer DEFAULT 0, trophy text DEFAULT 'normal', trophy_class text DEFAULT 'normal', avatar text DEFAULT '', grade_img text DEFAULT '', stars text DEFAULT '0', comment text DEFAULT '', play_count integer DEFAULT 0, raw_html text DEFAULT '', recent_json text DEFAULT '[]', top_json text DEFAULT '[]', clear_json text DEFAULT '[]', last_synced_at bigint DEFAULT 0, achievement_initialized_at bigint DEFAULT 0, created_at bigint DEFAULT 0, rating_card_blob bytea, rating_card_synced_at bigint DEFAULT 0, rating_card_version integer DEFAULT 0, server_region text DEFAULT 'intl', display_friend_code text DEFAULT '', total_play_count integer DEFAULT 0, map_json text DEFAULT '[]');
CREATE TABLE IF NOT EXISTS sessions (discord_user_id text PRIMARY KEY, cookie_json text NOT NULL DEFAULT '{}', friend_code text DEFAULT '', sync_token text DEFAULT '', avatar_blob text DEFAULT '', updated_at bigint DEFAULT 0, profile_private integer DEFAULT 0, extra_bookmarklets text DEFAULT '[]', preset_bookmarklets text DEFAULT '[]', default_server text DEFAULT 'intl', friend_code_intl text DEFAULT '', friend_code_jp text DEFAULT '', avatar_blob_intl text DEFAULT '', avatar_blob_jp text DEFAULT '', translate_titles integer DEFAULT 0);
CREATE TABLE IF NOT EXISTS jackets (user_id text NOT NULL, idx integer NOT NULL, data text NOT NULL, PRIMARY KEY(user_id,idx));
CREATE TABLE IF NOT EXISTS guild_settings (guild_id text PRIMARY KEY, auto_role integer DEFAULT 1);
CREATE TABLE IF NOT EXISTS song_jackets (music_id text PRIMARY KEY, data bytea NOT NULL, created_at bigint DEFAULT 0);
CREATE TABLE IF NOT EXISTS map_images (image_url text PRIMARY KEY, data bytea NOT NULL, created_at bigint DEFAULT 0);
CREATE TABLE IF NOT EXISTS constants_cache (key text PRIMARY KEY, data text NOT NULL, updated_at bigint DEFAULT 0);
CREATE TABLE IF NOT EXISTS song_aliases (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text NOT NULL, alias text NOT NULL, is_translation integer DEFAULT 0, created_at bigint DEFAULT 0, UNIQUE(title,alias));`,
  ],
  [2, `CREATE TABLE IF NOT EXISTS achievement_play_event_log (event_key text PRIMARY KEY, profile_key text NOT NULL, source_play_id text NOT NULL, is_baseline integer NOT NULL, played_at bigint NOT NULL, source_sequence integer NOT NULL, captured_at bigint NOT NULL, source_kind text DEFAULT 'history', achievement_val double precision NOT NULL, fc text DEFAULT '', sync text DEFAULT '', rating_up double precision, title text DEFAULT '', diff text DEFAULT '', level text DEFAULT '', music_kind text DEFAULT '', achievement_text text DEFAULT '', record_json text NOT NULL, payload_hash text NOT NULL);
CREATE TABLE IF NOT EXISTS achievement_play_event_log_state (profile_key text PRIMARY KEY, initialized_at bigint NOT NULL);
CREATE TABLE IF NOT EXISTS achievement_chart_best (profile_key text NOT NULL, chart_key text NOT NULL, achievement_val double precision NOT NULL DEFAULT 0, fc_rank integer NOT NULL DEFAULT 0, sync_rank integer NOT NULL DEFAULT 0, PRIMARY KEY(profile_key,chart_key));`,
  ],
  [3, `DO $migration$ BEGIN IF to_regclass('chart_record_baselines') IS NOT NULL THEN INSERT INTO achievement_chart_best(profile_key,chart_key,achievement_val,fc_rank,sync_rank) SELECT profile_key,title||'|'||music_kind||'|'||diff,max(achievement_val),max(CASE WHEN upper(replace(fc,' ','')) IN ('AP+','APP') THEN 4 WHEN upper(replace(fc,' ',''))='AP' THEN 3 WHEN upper(replace(fc,' ','')) IN ('FC+','FCP') THEN 2 WHEN upper(replace(fc,' ',''))='FC' THEN 1 ELSE 0 END),max(CASE WHEN upper(replace(sync,' ',''))='FDX+' THEN 5 WHEN upper(replace(sync,' ',''))='FDX' THEN 4 WHEN upper(replace(sync,' ',''))='FS+' THEN 3 WHEN upper(replace(sync,' ',''))='FS' THEN 2 WHEN upper(replace(sync,' ',''))='SYNC' THEN 1 ELSE 0 END) FROM chart_record_baselines WHERE title IS NOT NULL GROUP BY profile_key,title,music_kind,diff ON CONFLICT(profile_key,chart_key) DO UPDATE SET achievement_val=GREATEST(achievement_chart_best.achievement_val,excluded.achievement_val),fc_rank=GREATEST(achievement_chart_best.fc_rank,excluded.fc_rank),sync_rank=GREATEST(achievement_chart_best.sync_rank,excluded.sync_rank); END IF; IF to_regclass('achievement_play_event_log') IS NOT NULL THEN INSERT INTO achievement_chart_best(profile_key,chart_key,achievement_val,fc_rank,sync_rank) SELECT profile_key,title||'|'||music_kind||'|'||diff,max(achievement_val),max(CASE WHEN upper(replace(fc,' ','')) IN ('AP+','APP') THEN 4 WHEN upper(replace(fc,' ',''))='AP' THEN 3 WHEN upper(replace(fc,' ','')) IN ('FC+','FCP') THEN 2 WHEN upper(replace(fc,' ',''))='FC' THEN 1 ELSE 0 END),max(CASE WHEN upper(replace(sync,' ',''))='FDX+' THEN 5 WHEN upper(replace(sync,' ',''))='FDX' THEN 4 WHEN upper(replace(sync,' ',''))='FS+' THEN 3 WHEN upper(replace(sync,' ',''))='FS' THEN 2 WHEN upper(replace(sync,' ',''))='SYNC' THEN 1 ELSE 0 END) FROM achievement_play_event_log WHERE title IS NOT NULL AND title<>'' GROUP BY profile_key,title,music_kind,diff ON CONFLICT(profile_key,chart_key) DO UPDATE SET achievement_val=GREATEST(achievement_chart_best.achievement_val,excluded.achievement_val),fc_rank=GREATEST(achievement_chart_best.fc_rank,excluded.fc_rank),sync_rank=GREATEST(achievement_chart_best.sync_rank,excluded.sync_rank); END IF; END $migration$; DROP TABLE IF EXISTS daily_achievements; DROP TABLE IF EXISTS daily_achievement_snapshots; DROP TABLE IF EXISTS achievement_events; DROP TABLE IF EXISTS achievement_play_events; DROP TABLE IF EXISTS chart_record_baselines; DROP TABLE IF EXISTS chart_record_baseline_state; DROP TABLE IF EXISTS achievement_event_state; DROP TABLE IF EXISTS legacy_tables;`,],
  [4, `ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS chart_key text NOT NULL DEFAULT ''; ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS title text DEFAULT ''; ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS diff text DEFAULT ''; ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS music_kind text DEFAULT ''; UPDATE achievement_play_event_log SET chart_key=COALESCE(NULLIF(title,'')||'|'||NULLIF(music_kind,'')||'|'||NULLIF(diff,''),source_play_id) WHERE chart_key='';`,],
  [5, `ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS score_gain double precision; ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS is_meaningful integer;`,],
  [6, `UPDATE achievement_play_event_log SET score_gain=0 WHERE score_gain IS NULL; UPDATE achievement_play_event_log SET is_meaningful=0 WHERE is_meaningful IS NULL; CREATE INDEX IF NOT EXISTS idx_event_log_timeline ON achievement_play_event_log(profile_key,played_at DESC,source_sequence DESC,event_key);`,],
  [7, `ALTER TABLE sessions ADD COLUMN IF NOT EXISTS minimum_achievement double precision NOT NULL DEFAULT 95.0; ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS level_constant double precision; ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS achievement_before double precision; ALTER TABLE achievement_play_event_log ADD COLUMN IF NOT EXISTS rating_gain double precision;`,],
  // clearJson(전체 클리어 기록) 스냅샷을 곡별로 저장해두고 매 동기화마다 upsert하며 이전값과 비교한다.
  // achievement_chart_best(이벤트 로그 기반 캐시)와 달리 스크래핑 depth/NEW 마커에 의존하지 않는
  // 전체 클리어 페이지 자체가 기준이라, 트래킹 이전부터 있던 곡도 빠짐없이 기준치를 갖는다.
  [8, `CREATE TABLE IF NOT EXISTS chart_clears (profile_key text NOT NULL, chart_key text NOT NULL, achievement_val double precision NOT NULL DEFAULT 0, fc text DEFAULT '', sync text DEFAULT '', updated_at bigint DEFAULT 0, PRIMARY KEY(profile_key,chart_key));`,],
  // v8은 chart_clears를 빈 테이블로만 만들어서, 이미 존재하던 프로필은 배포 후 첫 동기화 때
  // 지금까지 친 모든 곡이 "0에서 상승"으로 한꺼번에 잡히는 사고가 났다(실제로 한 유저에게서
  // 1074개 성과가 튀어나와 렌더링/DB 부하로 서비스가 죽음). 기존 clear_json으로 빈 자리를 채운다.
  [9, `INSERT INTO chart_clears(profile_key,chart_key,achievement_val,fc,sync,updated_at)
SELECT p.friend_code,
       COALESCE(elem->>'title','')||'|'||COALESCE(elem->>'musicKind','')||'|'||COALESCE(elem->>'diff',''),
       COALESCE((elem->>'achievementVal')::double precision,0),
       COALESCE(elem->>'fc',''),
       COALESCE(elem->>'sync',''),
       0
FROM profiles p, jsonb_array_elements(p.clear_json::jsonb) AS elem
WHERE p.clear_json IS NOT NULL AND p.clear_json NOT IN ('','[]') AND COALESCE((elem->>'achievementVal')::double precision,0)>0
ON CONFLICT (profile_key,chart_key) DO NOTHING;`,],
  // 목표(todo) 추적: discord 유저별 목표 + 매 동기화마다 갱신되는 진행률 스냅샷.
  [10, `CREATE TABLE IF NOT EXISTS user_goals (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, discord_user_id text NOT NULL, kind text NOT NULL, spec_json text NOT NULL DEFAULT '{}', label text NOT NULL DEFAULT '', progress double precision NOT NULL DEFAULT 0, current_json text NOT NULL DEFAULT '{}', completed_at bigint NOT NULL DEFAULT 0, created_at bigint NOT NULL DEFAULT 0, updated_at bigint NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_user_goals_owner ON user_goals(discord_user_id, completed_at, id);`,],
  // sessions.policy_ack: 사용자가 마지막으로 고지받은 개인정보처리방침 버전(src/policy.ts POLICY_VERSION).
  // 0이면 아직 고지 전. 북마클릿/확장 동기화 또는 슬래시 명령 시 낡았으면 1회 고지하고 갱신한다.
  [11, `ALTER TABLE sessions ADD COLUMN IF NOT EXISTS policy_ack integer NOT NULL DEFAULT 0;`,],
  // song_aliases.id는 GENERATED BY DEFAULT AS IDENTITY라, 시드/덤프를 명시적 id로 넣으면
  // 아이덴티티 시퀀스가 그대로 1에 머문다. 그 상태에서 새 별명을 추가하면 id=1로 들어가려다
  // song_aliases_pkey 중복으로 실패한다(ON CONFLICT(title,alias)로는 안 잡힘).
  // 시퀀스를 현재 최대 id 다음으로 맞춘다.
  [12, `SELECT setval(pg_get_serial_sequence('song_aliases','id'), COALESCE((SELECT MAX(id) FROM song_aliases), 0) + 1, false);`,],
  // bot_messages: 봇 출력 문구의 오버라이드. key는 src/messages.ts의 카탈로그 키이고
  // 행이 없으면 코드의 기본값이 쓰인다(삭제 = 기본값 복원).
  [13, `CREATE TABLE IF NOT EXISTS bot_messages (key text PRIMARY KEY, text text NOT NULL, updated_at bigint NOT NULL DEFAULT 0);`,],
  // rating_snapshots: 하루(04:00 KST 기준 play-day)별 레이팅 대상 50곡 + 총합 레이팅.
  // profiles.top_json 은 동기화마다 덮어써져 이력이 없으므로, 과거 레이팅표 조회를 위해
  // 별도로 남긴다. 같은 날 여러 번 동기화하면 마지막 상태로 갱신된다.
  [14, `CREATE TABLE IF NOT EXISTS rating_snapshots (
    profile_key text NOT NULL,
    play_day text NOT NULL,
    top_json text NOT NULL,
    rating integer NOT NULL DEFAULT 0,
    synced_at bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (profile_key, play_day)
  );`,],
  // 공지 폴링. news_channels 는 서버별 출처별 게시 채널, news_seen 은 중복 게시 방지,
  // news_feed_state 는 조건부 요청(ETag/Last-Modified)용 상태. source 는 'jp' | 'intl'.
  [15, `CREATE TABLE IF NOT EXISTS news_channels (
    guild_id text NOT NULL,
    source text NOT NULL,
    channel_id text NOT NULL,
    PRIMARY KEY (guild_id, source)
  );
  CREATE TABLE IF NOT EXISTS news_seen (
    source text NOT NULL,
    item_id text NOT NULL,
    posted_at bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (source, item_id)
  );
  CREATE TABLE IF NOT EXISTS news_feed_state (
    source text PRIMARY KEY,
    etag text NOT NULL DEFAULT '',
    last_modified text NOT NULL DEFAULT '',
    checked_at bigint NOT NULL DEFAULT 0
  );`,],
  // 공지 본문/번역 보관. 버튼(customId 100자 제한)에는 키만 싣고 내용은 여기서 꺼낸다.
  // 오래된 메시지의 버튼도 눌리므로 봇 재시작과 무관하게 남아 있어야 한다.
  [16, `CREATE TABLE IF NOT EXISTS news_articles (
    source text NOT NULL,
    item_id text NOT NULL,
    title text NOT NULL DEFAULT '',
    title_ko text NOT NULL DEFAULT '',
    url text NOT NULL DEFAULT '',
    body text NOT NULL DEFAULT '',
    body_ko text NOT NULL DEFAULT '',
    created_at bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (source, item_id)
  );`,],
];

function hash(text: string): string { return crypto.createHash("sha256").update(text).digest("hex"); }
function fcRank(v: string): number { const x=v.trim().toUpperCase().replace(/\s+/g, ""); return x === "AP+" || x === "APP" ? 4 : x === "AP" ? 3 : x === "FC+" || x === "FCP" ? 2 : x === "FC" ? 1 : 0; }
function syncRank(v: string): number { const x=v.trim().toUpperCase().replace(/\s+/g, ""); return x === "FDX+" || x === "FDXP" ? 5 : x === "FDX" ? 4 : x === "FS+" || x === "FSP" ? 3 : x === "FS" ? 2 : x === "SYNC" || x === "S" ? 1 : 0; }

export class PostgresStorage {
  readonly pool: Pool;
  constructor(config: string | PoolConfig) { this.pool = new Pool(typeof config === "string" ? { connectionString: config } : config); }
  async initialize(): Promise<void> {
    const c = await this.pool.connect();
    try { await c.query("BEGIN"); await c.query("CREATE TABLE IF NOT EXISTS storage_migrations (version integer PRIMARY KEY, applied_at bigint NOT NULL, checksum text NOT NULL)");
      for (const [version, sql] of MIGRATIONS) { const checksum=hash(sql); const old=await c.query<{checksum:string}>("SELECT checksum FROM storage_migrations WHERE version=$1",[version]);
        // v0.7.10 recorded the checksum of one monolithic schema as v1.  It
        // is historical data, not a checksum for this migration unit: never
        // rewrite it and do not reject an otherwise usable old database.
        const legacyV1 = version === 1 && !!old.rows[0];
        if (legacyV1) { await c.query(sql); continue; }
        if(old.rows[0] && old.rows[0].checksum!==checksum && !legacyV1) throw new Error(`migration ${version} checksum mismatch`);
        if(!old.rows[0]) { await c.query(sql); await c.query("INSERT INTO storage_migrations(version,applied_at,checksum) VALUES($1,$2,$3)",[version,Date.now(),checksum]); }
      }
      await c.query("COMMIT");
    } catch(e) { await c.query("ROLLBACK"); throw e; } finally { c.release(); }
  }
  async close(){ await this.pool.end(); }
  private async q<T=any>(sql:string, values:unknown[]=[]):Promise<T[]> { return (await this.pool.query(sql,values)).rows as T[]; }
  private async tx<T>(fn:(c:PoolClient)=>Promise<T>):Promise<T>{const c=await this.pool.connect();try{await c.query("BEGIN");const x=await fn(c);await c.query("COMMIT");return x;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}

  async cacheProfile(p:MaimaiProfile, playCount:number, recentJson="[]", topJson="[]", clearJson="[]", server:Db.MaimaiServer="intl", mapJson="[]"){const fc=p.friendCode??"me", key=`${server}:${fc}`, now=Date.now();await this.q(`INSERT INTO profiles(friend_code,display_friend_code,server_region,player_name,rating,rating_max,trophy,trophy_class,avatar,grade_img,stars,comment,play_count,total_play_count,raw_html,recent_json,top_json,clear_json,map_json,last_synced_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,'',$15,$16,$17,$18,$19,$19) ON CONFLICT(friend_code) DO UPDATE SET display_friend_code=excluded.display_friend_code,server_region=excluded.server_region,player_name=excluded.player_name,rating=excluded.rating,rating_max=excluded.rating_max,trophy=excluded.trophy,trophy_class=excluded.trophy_class,avatar=excluded.avatar,grade_img=excluded.grade_img,stars=excluded.stars,comment=excluded.comment,play_count=excluded.play_count,total_play_count=excluded.total_play_count,recent_json=excluded.recent_json,top_json=excluded.top_json,clear_json=excluded.clear_json,map_json=excluded.map_json,last_synced_at=excluded.last_synced_at`,[key,fc,server,p.playerName,p.rating,p.ratingMax,p.trophy,p.trophyClass,p.avatar,p.gradeImg,p.stars,p.comment??"",playCount,p.totalPlayCount??playCount,recentJson,topJson,clearJson,mapJson,now]);return key;}
  async getCachedProfile(fc:string){const r=await this.q<any>(`SELECT friend_code AS "profileKey",COALESCE(NULLIF(display_friend_code,''),friend_code) AS "friendCode",COALESCE(server_region,'intl') AS server,player_name AS "playerName",rating,rating_max AS "ratingMax",trophy,trophy_class AS "trophyClass",avatar,grade_img AS "gradeImg",stars,comment,play_count AS "playCount",COALESCE(total_play_count,0) AS "totalPlayCount",last_synced_at AS "lastSyncedAt",recent_json AS "recentJson",top_json AS "topJson",clear_json AS "clearJson",COALESCE(map_json,'[]') AS "mapJson" FROM profiles WHERE friend_code=$1 OR display_friend_code=$1 LIMIT 1`,[fc]);if(r[0])r[0].lastSyncedAt=Number(r[0].lastSyncedAt);return r[0]??null;}
  async getAllCachedProfiles(){return this.q(`SELECT friend_code AS "profileKey",COALESCE(NULLIF(display_friend_code,''),friend_code) AS "friendCode",server_region AS server,player_name AS "playerName",rating,rating_max AS "ratingMax",trophy,trophy_class AS "trophyClass",avatar,grade_img AS "gradeImg",stars,comment,play_count AS "playCount",total_play_count AS "totalPlayCount",last_synced_at AS "lastSyncedAt",recent_json AS "recentJson",top_json AS "topJson",clear_json AS "clearJson",map_json AS "mapJson" FROM profiles`);}
  async deleteCachedProfile(fc:string){await this.q("DELETE FROM profiles WHERE friend_code=$1",[fc]);}

  // 레이팅 대상 50곡 스냅샷. topJson 은 마크(FC/Sync)·ST/DX 보정까지 끝낸 상태로 넘어온다.
  async saveRatingSnapshot(profileKey:string, playDay:string, topJson:string, rating:number, syncedAt:number){
    await this.q(`INSERT INTO rating_snapshots(profile_key,play_day,top_json,rating,synced_at) VALUES($1,$2,$3,$4,$5)
      ON CONFLICT(profile_key,play_day) DO UPDATE SET top_json=excluded.top_json,rating=excluded.rating,synced_at=excluded.synced_at`,
      [profileKey,playDay,topJson,Math.round(rating)||0,syncedAt]);
  }
  // 요청 날짜 이하 중 가장 최근 스냅샷. 갱신하지 않은 날의 레이팅표는 직전 갱신 시점
  // 상태와 같으므로, 정확히 일치하는 행이 없어도 직전 기록으로 답한다.
  // 호출부는 반환된 playDay 가 요청 날짜와 다르면 그 사실을 함께 표시한다.
  async getRatingSnapshot(profileKey:string, playDay:string){
    const r=await this.q<any>(`SELECT play_day AS "playDay",top_json AS "topJson",rating,synced_at AS "syncedAt" FROM rating_snapshots WHERE profile_key=$1 AND play_day <= $2 ORDER BY play_day DESC LIMIT 1`,[profileKey,playDay]);
    if(!r[0]) return null;
    return {...r[0], rating:Number(r[0].rating), syncedAt:Number(r[0].syncedAt)};
  }
  // 조회 가능한 날짜 범위 안내용. 스냅샷이 없는 날짜를 요청했을 때 쓴다.
  async getRatingSnapshotRange(profileKey:string){
    const r=await this.q<any>(`SELECT MIN(play_day) AS "first",MAX(play_day) AS "last",COUNT(*)::int AS "count" FROM rating_snapshots WHERE profile_key=$1`,[profileKey]);
    return r[0]?.count ? r[0] as {first:string;last:string;count:number} : null;
  }

  // clearJson 스냅샷(chart_clears)을 곡별로 upsert하면서 갱신 전 값을 같은 쿼리에서 돌려받는다.
  // CTE는 이 문(statement)의 쓰기가 반영되기 전 스냅샷을 보므로 "직전 값 vs 이번 값" 비교가 원자적이다.
  // 오른 채보만 걸러서 반환 — 트래킹 시작 전부터 있던 곡이든 방금 처음 친 곡이든 chart_clears에 값이
  // 없으면 0을 기존값으로 보고, 그 자체가 정확한 "진짜 처음 클리어"이므로 잘못된 0 표시가 아니다.
  async upsertChartClears(profileKey:string, records:readonly Db.ChartClearInput[]):Promise<Db.ChartClearDiff[]>{
    if(!records.length) return [];
    const keys=records.map(r=>r.chartKey), vals=records.map(r=>r.achievementVal), fcs=records.map(r=>r.fc||""), syncs=records.map(r=>r.sync||""), now=Date.now();
    const rows=await this.q<any>(`WITH incoming AS (SELECT * FROM unnest($2::text[],$3::double precision[],$4::text[],$5::text[]) AS t(chart_key,achievement_val,fc,sync)),
old AS (SELECT chart_key,achievement_val,fc,sync FROM chart_clears WHERE profile_key=$1),
upserted AS (INSERT INTO chart_clears(profile_key,chart_key,achievement_val,fc,sync,updated_at) SELECT $1,i.chart_key,i.achievement_val,i.fc,i.sync,$6 FROM incoming i ON CONFLICT(profile_key,chart_key) DO UPDATE SET achievement_val=excluded.achievement_val,fc=excluded.fc,sync=excluded.sync,updated_at=excluded.updated_at RETURNING chart_key,achievement_val,fc,sync)
SELECT u.chart_key AS "chartKey",u.achievement_val AS "achievementVal",u.fc,u.sync,COALESCE(o.achievement_val,0) AS "achievementBefore",COALESCE(o.fc,'') AS "oldFc",COALESCE(o.sync,'') AS "oldSync" FROM upserted u LEFT JOIN old o ON o.chart_key=u.chart_key`,
      [profileKey,keys,vals,fcs,syncs,now]);
    // 순수 SYNC(rank 1)는 멀티플레이에 참여하기만 해도 붙는 등급이라 실력 성과로 보기 어렵다.
    // FS 이상(rank>=2)으로 올라간 경우만 sync 쪽 성과 트리거로 인정한다.
    // fcImproved/syncImproved: 이번에 등급이 실제로 올랐는지. 소비자(성과 이벤트)가
    // "이미 갖고 있던" 마크를 붙이지 않도록 직전값 대비 결과를 함께 돌려준다.
    return rows.map((r:any)=>{
      const sr=syncRank(r.sync), oldSr=syncRank(r.oldSync);
      const fcImproved=fcRank(r.fc)>fcRank(r.oldFc);
      const syncImproved=sr>=2&&sr>oldSr;
      const scoreImproved=Number(r.achievementVal)>Number(r.achievementBefore);
      return {chartKey:r.chartKey,achievementVal:Number(r.achievementVal),achievementBefore:Number(r.achievementBefore),fc:r.fc,sync:r.sync,fcImproved,syncImproved,scoreImproved};
    }).filter((d:any)=>d.scoreImproved||d.fcImproved||d.syncImproved)
      .map(({scoreImproved,...d}:any)=>d);
  }
  async saveAchievementPlayEventLogBatch(rawEvents:readonly Db.AchievementPlayEventLogInput[], capturedAt=Date.now()) {
    if(!rawEvents.length) return "ok";
    // 정상적인 하루 성과는 수십 개를 넘기지 않는다. 훨씬 크면 거의 확실히 버그
    // (예: 마이그레이션 백필 누락으로 전체 클리어 기록이 한꺼번에 "신규"로 잡히는 경우)이므로,
    // 동기화 자체가 죽지 않도록 앞쪽 일부만 기록하고 나머지는 버린다.
    const MAX_EVENTS_PER_BATCH = 200;
    if(rawEvents.length>MAX_EVENTS_PER_BATCH) console.warn(`[achievement] batch too large (${rawEvents.length} events for ${rawEvents[0].profileKey}), truncating to ${MAX_EVENTS_PER_BATCH}`);
    const events = rawEvents.length>MAX_EVENTS_PER_BATCH ? rawEvents.slice(0,MAX_EVENTS_PER_BATCH) : rawEvents;
    const profile=events[0].profileKey;
    const seen=new Map<string,string>();
    for(const e of events){if(e.profileKey!==profile||!e.sourcePlayId?.trim()||!e.chartKey||!Number.isFinite(e.playedAt)||!Number.isFinite(e.achievementVal))throw new Error("invalid event batch");const id=e.sourcePlayId.trim(), sig=JSON.stringify(e);if(seen.has(id)&&seen.get(id)!==sig)throw new Error("conflicting sourcePlayId");seen.set(id,sig);}
    return this.tx(async c=>{await c.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[profile]);
      const ordered=[...events].sort((a,b)=>a.playedAt-b.playedAt);
      for(const e of ordered){const id=e.sourcePlayId!.trim(), key=hash(`${profile}\x1f${id}`), payload=hash(JSON.stringify(e));const exists=await c.query<{event_key:string}>("SELECT event_key FROM achievement_play_event_log WHERE profile_key=$1 AND source_play_id=$2 OR event_key=$3",[profile,id,key]);if(exists.rowCount){if(e.ratingUp!=null)await c.query("UPDATE achievement_play_event_log SET rating_up=COALESCE(rating_up,$1) WHERE event_key=$2",[e.ratingUp,exists.rows[0].event_key]);continue;}
        const score=Number(e.achievementVal), before=Number(e.achievementBefore);const gain=Math.max(0,score-before);const suppliedLevelConstant=e.levelConstant==null?null:Number(e.levelConstant);const server=profile.startsWith("jp:")?"jp":"intl";const levelConstant=suppliedLevelConstant!=null&&Number.isFinite(suppliedLevelConstant)?suppliedLevelConstant:getConstant(e.title,e.musicKind,e.diff,server)??levelToNumber(e.level);
        // 레이팅 상승은 DX NET 상세 페이지의 (+N) 파싱값(e.ratingUp)만 신뢰한다.
        // 달성률 기반 추정치는 (a) 베스트 50 진입 여부를 알 수 없고 (b) 이전 기록이
        // 없는 채보(achievementBefore=0)에서 곡 레이팅 전체를 상승분으로 잡아
        // "레이팅 +300" 같은 값을 만들어내므로 사용하지 않는다. 파싱값이 없으면 0.
        // 宴/코스 등 다른 모드 상세 페이지에선 (+N) 이 레이팅 증가분이 아닌 값으로
        // 잘못 잡히므로, 단일 채보가 물리적으로 줄 수 있는 최대 곡 레이팅
        // (상수 불명 시 이론상 최대치 338)을 넘는 파싱값은 버린다.
        const parsedRatingUp=Number.isFinite(e.ratingUp)?Math.max(0,Number(e.ratingUp)):null;const ratingUpCeiling=levelConstant!=null&&Number.isFinite(levelConstant)?calcSongRating(score,levelConstant,e.fc):338;const ratingGain=parsedRatingUp!=null&&parsedRatingUp<=ratingUpCeiling?parsedRatingUp:0;
        await c.query(`INSERT INTO achievement_play_event_log(event_key,profile_key,source_play_id,chart_key,is_baseline,played_at,source_sequence,captured_at,source_kind,achievement_val,fc,sync,rating_up,title,diff,level,music_kind,achievement_text,record_json,payload_hash,score_gain,is_meaningful,level_constant,achievement_before,rating_gain) VALUES($1,$2,$3,$4,0,$5,$6,$7,'clear_diff',$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,1,$20,$21,$22)`,[key,profile,id,e.chartKey,e.playedAt,e.sourceSequence,e.capturedAt??capturedAt,score,e.fc,e.sync,e.ratingUp??null,e.title,e.diff,e.level,e.musicKind,e.achievementText,e.recordJson,payload,Number.isFinite(gain)?gain:0,levelConstant,before,Number.isFinite(ratingGain)?ratingGain:0]);
      } return "ok";});
  }
  // 상세 페이지의 (+N) 은 이벤트가 만들어지는 동기화에서 늘 함께 오지는 않는다.
  // (DX NET 레이트리밋으로 상세 수집 실패, 상세만 나중 동기화에서 도착 등)
  // 매 동기화마다 이번에 받은 상세 페이지로 rating_up 이 비어 있는 이벤트를 메운다.
  // 이벤트 생성 조건(달성률 상승)과 무관하게 동작해야 하므로 배치 저장과 분리한다.
  async backfillEventRatingUp(profileKey:string, entries:readonly {sourcePlayId:string;ratingUp:number}[]):Promise<number>{
    const byId=new Map<string,number>();
    for(const e of entries){if(e.sourcePlayId&&Number.isFinite(e.ratingUp)&&e.ratingUp>=0)byId.set(e.sourcePlayId,Number(e.ratingUp));}
    if(!byId.size) return 0;
    const rows=await this.q<any>(`SELECT event_key AS "eventKey",source_play_id AS "sourcePlayId",achievement_val AS "achievementVal",level_constant AS "levelConstant",fc FROM achievement_play_event_log WHERE profile_key=$1 AND rating_up IS NULL AND source_play_id = ANY($2::text[])`,[profileKey,[...byId.keys()]]);
    let filled=0;
    for(const r of rows){
      const ru=byId.get(r.sourcePlayId); if(ru===undefined) continue;
      const lc=r.levelConstant==null?null:Number(r.levelConstant);
      // 저장 경로와 같은 상한 검증. 宴/코스 상세의 (+N) 오탐을 레이팅 상승으로 쓰지 않는다.
      const ceiling=lc!=null&&Number.isFinite(lc)?calcSongRating(Number(r.achievementVal),lc,r.fc):338;
      await this.q(`UPDATE achievement_play_event_log SET rating_up=$1,rating_gain=$2 WHERE event_key=$3`,[ru,ru<=ceiling?ru:0,r.eventKey]);
      filled++;
    }
    return filled;
  }
  async getAchievementPlayEventLog(k:string,from?:number,to?:number){const r=await this.q<any>(`SELECT event_key AS "eventKey",profile_key AS "profileKey",source_play_id AS "sourcePlayId",chart_key AS "chartKey",is_baseline AS "isBaseline",played_at AS "playedAt",source_sequence AS "sourceSequence",captured_at AS "capturedAt",source_kind AS "sourceKind",achievement_val AS "achievementVal",fc,sync,rating_up AS "ratingUp",title,diff,level,music_kind AS "musicKind",achievement_text AS "achievementText",record_json AS "recordJson",payload_hash AS "payloadHash",score_gain AS "scoreGain",is_meaningful AS "isMeaningful",level_constant AS "levelConstant",achievement_before AS "achievementBefore",rating_gain AS "ratingGain" FROM achievement_play_event_log WHERE profile_key=$1 AND ($2::bigint IS NULL OR played_at >= $2) AND ($3::bigint IS NULL OR played_at < $3) ORDER BY played_at DESC,source_sequence DESC,event_key DESC`,[k,from??null,to??null]);return r.map(x=>({...x,playedAt:Number(x.playedAt),capturedAt:Number(x.capturedAt),sourceSequence:Number(x.sourceSequence),isBaseline:Number(x.isBaseline),isMeaningful:Number(x.isMeaningful),scoreGain:Number(x.scoreGain),levelConstant:x.levelConstant==null?null:Number(x.levelConstant),achievementBefore:Number(x.achievementBefore??0),ratingGain:Math.max(0,Number(x.ratingGain)||0)}));}
  async getDailyAchievementSummaries(discordUserId:string,from:number,to:number){const session=await this.q<any>("SELECT friend_code,default_server FROM sessions WHERE discord_user_id=$1",[discordUserId]);const stored=session[0]?.friend_code;const profileKey=stored?(/^(?:intl|jp):/.test(stored)?stored:`${session[0]?.default_server==='jp'?'jp':'intl'}:${stored}`):discordUserId;const threshold=await this.getAchievementMinimum(discordUserId);return (await this.getAchievementPlayEventLog(profileKey,from,to)).filter((x:any)=>x.isBaseline===0&&x.isMeaningful===1).reduce((a:any[],x:any)=>{const old=a.find(y=>y.chartKey===x.chartKey);if(!old&&(x.achievementVal>=threshold||fcRank(x.fc)>0||syncRank(x.sync)>=2))a.push({...x,achievementGain:Math.max(0,Number(x.achievementVal)-Number(x.achievementBefore??0)),achievementAfter:Number(x.achievementVal),ratingGain:Math.max(0,Number(x.ratingGain)||0)});return a;},[]);}
  // 성과 로그의 보유 범위. 과거 레이팅표 역산이 가능한 하한을 안내할 때 쓴다.
  async getAchievementLogRange(profileKey:string){
    const r=await this.q<any>(`SELECT MIN(played_at) AS "first",MAX(played_at) AS "last",COUNT(*)::int AS "count" FROM achievement_play_event_log WHERE profile_key=$1`,[profileKey]);
    return r[0]?.count ? {first:Number(r[0].first),last:Number(r[0].last),count:Number(r[0].count)} : null;
  }
  async getAchievementMinimum(id:string){const r=await this.q<any>("SELECT minimum_achievement FROM sessions WHERE discord_user_id=$1",[id]);return Number(r[0]?.minimum_achievement??95);}
  async setAchievementMinimum(id:string,v:number){const value=Number.isFinite(v)?Math.min(100,Math.max(0,v)):95;await this.q("INSERT INTO sessions(discord_user_id,minimum_achievement) VALUES($1,$2) ON CONFLICT(discord_user_id) DO UPDATE SET minimum_achievement=excluded.minimum_achievement",[id,value]);}

  // ─── 목표(todo) ────────────────────────────────────────────────────────────
  async listGoals(id:string):Promise<Db.GoalRow[]>{const r=await this.q<any>("SELECT id,discord_user_id AS \"discordUserId\",kind,spec_json AS \"specJson\",label,progress,current_json AS \"currentJson\",completed_at AS \"completedAt\",created_at AS \"createdAt\",updated_at AS \"updatedAt\" FROM user_goals WHERE discord_user_id=$1 ORDER BY (completed_at<>0) ASC, id ASC",[id]);return r.map(x=>({...x,id:Number(x.id),progress:Number(x.progress),completedAt:Number(x.completedAt),createdAt:Number(x.createdAt),updatedAt:Number(x.updatedAt)}));}
  async countGoals(id:string){const r=await this.q<any>("SELECT count(*)::int n FROM user_goals WHERE discord_user_id=$1",[id]);return Number(r[0]?.n??0);}
  async addGoal(id:string,kind:string,specJson:string,label:string){const now=Date.now();const r=await this.q<any>("INSERT INTO user_goals(discord_user_id,kind,spec_json,label,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$5) RETURNING id",[id,kind,specJson,label,now]);return Number(r[0].id);}
  async deleteGoal(id:string,goalId:number){const r=await this.pool.query("DELETE FROM user_goals WHERE discord_user_id=$1 AND id=$2",[id,goalId]);return (r.rowCount??0)>0;}
  async updateGoalProgress(goalId:number,progress:number,currentJson:string,completedAt:number){await this.q("UPDATE user_goals SET progress=$2,current_json=$3,completed_at=CASE WHEN $4>0 AND completed_at=0 THEN $4 WHEN $4=0 THEN 0 ELSE completed_at END,updated_at=$5 WHERE id=$1",[goalId,progress,currentJson,completedAt,Date.now()]);}

  async saveUserSession(id:string,cookie:string,fc="",server:Db.MaimaiServer="intl"){const col=server==='jp'?'friend_code_jp':'friend_code_intl';await this.q(`INSERT INTO sessions(discord_user_id,cookie_json,friend_code,${col},default_server,updated_at) VALUES($1,$2,$3,$3,$4,$5) ON CONFLICT(discord_user_id) DO UPDATE SET cookie_json=excluded.cookie_json,default_server=CASE WHEN sessions.friend_code='' THEN excluded.default_server ELSE sessions.default_server END,friend_code=CASE WHEN sessions.friend_code='' OR sessions.default_server=excluded.default_server THEN excluded.friend_code ELSE sessions.friend_code END,${col}=excluded.${col},updated_at=excluded.updated_at`,[id,encrypt(cookie),fc,server,Date.now()]);}
  async loadUserSession(id:string){const r=await this.q<any>("SELECT cookie_json,friend_code FROM sessions WHERE discord_user_id=$1",[id]);if(!r[0])return null;try{decrypt(r[0].cookie_json);return {friendCode:r[0].friend_code||""};}catch{return null;}}
  async getUserFriendCode(id:string){const r=await this.q<any>("SELECT friend_code FROM sessions WHERE discord_user_id=$1",[id]);return r[0]?.friend_code||null;}
  async getUserFriendCodeForServer(id:string,s:Db.MaimaiServer){const col=s==='jp'?'friend_code_jp':'friend_code_intl';const r=await this.q<any>(`SELECT ${col} AS friend_code FROM sessions WHERE discord_user_id=$1`,[id]);return r[0]?.friend_code||null;}
  async getUserDefaultServer(id:string):Promise<Db.MaimaiServer>{const r=await this.q<any>("SELECT default_server FROM sessions WHERE discord_user_id=$1",[id]);return r[0]?.default_server==='jp'?'jp':'intl';}
  async setUserDefaultServer(id:string,s:Db.MaimaiServer){const col=s==='jp'?'friend_code_jp':'friend_code_intl';const r=await this.q<any>(`SELECT ${col} AS region_friend_code,friend_code AS current_friend_code FROM sessions WHERE discord_user_id=$1`,[id]);const fc=r[0]?.region_friend_code||r[0]?.current_friend_code||'';await this.q(`INSERT INTO sessions(discord_user_id,default_server,friend_code) VALUES($1,$2,$3) ON CONFLICT(discord_user_id) DO UPDATE SET default_server=excluded.default_server,friend_code=excluded.friend_code`,[id,s,fc]);return 1;}
  async getUserSyncToken(id:string){const r=await this.q<any>("SELECT sync_token FROM sessions WHERE discord_user_id=$1",[id]);if(r[0]?.sync_token)return r[0].sync_token;const t=crypto.randomBytes(12).toString("hex");await this.q("INSERT INTO sessions(discord_user_id,sync_token) VALUES($1,$2) ON CONFLICT(discord_user_id) DO UPDATE SET sync_token=excluded.sync_token",[id,t]);return t;}
  async findUserBySyncToken(t:string){const r=await this.q<any>("SELECT discord_user_id FROM sessions WHERE sync_token=$1",[t]);return r[0]?.discord_user_id??null;}
  async saveAvatarBlob(id:string,s:Db.MaimaiServer,b:string){const col=s==='jp'?'avatar_blob_jp':'avatar_blob_intl';await this.q(`INSERT INTO sessions(discord_user_id,${col},avatar_blob) VALUES($1,$2,$2) ON CONFLICT(discord_user_id) DO UPDATE SET ${col}=excluded.${col},avatar_blob=excluded.avatar_blob`,[id,b]);}
  async getAvatarBlob(id:string,s?:Db.MaimaiServer){const r=await this.q<any>("SELECT avatar_blob,avatar_blob_intl,avatar_blob_jp FROM sessions WHERE discord_user_id=$1",[id]);if(!r[0])return null;const b=s==='jp'?r[0].avatar_blob_jp:s==='intl'?r[0].avatar_blob_intl:r[0].avatar_blob_intl||r[0].avatar_blob;return b?Buffer.from(b,'base64'):null;}
  async saveJacket(id:string,i:number,b:string){await this.q("INSERT INTO jackets VALUES($1,$2,$3) ON CONFLICT(user_id,idx) DO UPDATE SET data=excluded.data",[id,i,b]);} async getJacket(id:string,i:number){const r=await this.q<any>("SELECT data FROM jackets WHERE user_id=$1 AND idx=$2",[id,i]);const m=r[0]?.data?.match(/^data:image\/\w+;base64,(.+)$/);return m?Buffer.from(m[1],'base64'):null;}
  async getSongJacket(id:string){const r=await this.q<any>("SELECT data FROM song_jackets WHERE music_id=$1",[id]);return r[0]?.data??null;} async saveSongJacket(id:string,b:Buffer){await this.q("INSERT INTO song_jackets VALUES($1,$2,$3) ON CONFLICT(music_id) DO UPDATE SET data=excluded.data",[id,b,Date.now()]);}
  async getMapImage(u:string){const r=await this.q<any>("SELECT data FROM map_images WHERE image_url=$1",[u]);return r[0]?.data??null;} async saveMapImage(u:string,b:Buffer){await this.q("INSERT INTO map_images VALUES($1,$2,$3) ON CONFLICT(image_url) DO UPDATE SET data=excluded.data",[u,b,Date.now()]);}
  // ─── 공지 폴링 ─────────────────────────────────────────────────────────────
  async listNewsChannels(source:string){return this.q<{guildId:string;channelId:string}>(`SELECT guild_id AS "guildId",channel_id AS "channelId" FROM news_channels WHERE source=$1`,[source]);}
  async getNewsChannels(guildId:string){return this.q<{source:string;channelId:string}>(`SELECT source,channel_id AS "channelId" FROM news_channels WHERE guild_id=$1`,[guildId]);}
  async setNewsChannel(guildId:string,source:string,channelId:string){await this.q(`INSERT INTO news_channels(guild_id,source,channel_id) VALUES($1,$2,$3) ON CONFLICT(guild_id,source) DO UPDATE SET channel_id=excluded.channel_id`,[guildId,source,channelId]);}
  async clearNewsChannel(guildId:string,source:string){const r=await this.pool.query("DELETE FROM news_channels WHERE guild_id=$1 AND source=$2",[guildId,source]);return (r.rowCount??0)>0;}

  async getSeenNewsIds(source:string){const r=await this.q<{itemId:string}>(`SELECT item_id AS "itemId" FROM news_seen WHERE source=$1`,[source]);return new Set(r.map(x=>x.itemId));}
  async markNewsSeen(source:string,itemIds:readonly string[],postedAt=Date.now()){
    if(!itemIds.length) return;
    await this.q(`INSERT INTO news_seen(source,item_id,posted_at) SELECT $1,x,$3 FROM unnest($2::text[]) AS x ON CONFLICT(source,item_id) DO NOTHING`,[source,[...itemIds],postedAt]);
  }
  // 테스트용: 특정 항목을 '안 본 것'으로 되돌린다.
  async deleteNewsSeen(source:string,itemId:string){const r=await this.pool.query("DELETE FROM news_seen WHERE source=$1 AND item_id=$2",[source,itemId]);return (r.rowCount??0)>0;}
  async saveNewsArticle(a:{source:string;itemId:string;title:string;titleKo:string;url:string;body:string;bodyKo:string},createdAt=Date.now()){
    await this.q(`INSERT INTO news_articles(source,item_id,title,title_ko,url,body,body_ko,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
      ON CONFLICT(source,item_id) DO UPDATE SET title=excluded.title,title_ko=excluded.title_ko,url=excluded.url,body=excluded.body,body_ko=excluded.body_ko`,
      [a.source,a.itemId,a.title,a.titleKo,a.url,a.body,a.bodyKo,createdAt]);
  }
  async getNewsArticle(source:string,itemId:string){
    const r=await this.q<any>(`SELECT source,item_id AS "itemId",title,title_ko AS "titleKo",url,body,body_ko AS "bodyKo" FROM news_articles WHERE source=$1 AND item_id=$2`,[source,itemId]);
    return r[0]??null;
  }
  // 본문은 계속 쌓이기만 하므로 오래된 것은 지운다. 버튼은 "기간 지남" 안내로 응답한다.
  async pruneNewsArticles(olderThanMs:number){
    const r=await this.pool.query("DELETE FROM news_articles WHERE created_at < $1",[Date.now()-olderThanMs]);
    return r.rowCount??0;
  }
  async getNewsFeedState(source:string){const r=await this.q<any>(`SELECT etag,last_modified AS "lastModified",checked_at AS "checkedAt" FROM news_feed_state WHERE source=$1`,[source]);return r[0]?{...r[0],checkedAt:Number(r[0].checkedAt)}:null;}
  async setNewsFeedState(source:string,etag:string,lastModified:string,checkedAt=Date.now()){
    await this.q(`INSERT INTO news_feed_state(source,etag,last_modified,checked_at) VALUES($1,$2,$3,$4) ON CONFLICT(source) DO UPDATE SET etag=excluded.etag,last_modified=excluded.last_modified,checked_at=excluded.checked_at`,[source,etag,lastModified,checkedAt]);
  }

  async getGuildSetting(id:string){const r=await this.q<any>("SELECT auto_role FROM guild_settings WHERE guild_id=$1",[id]);return r[0]?.auto_role!==0;} async setGuildSetting(id:string,v:boolean){await this.q("INSERT INTO guild_settings VALUES($1,$2) ON CONFLICT(guild_id) DO UPDATE SET auto_role=excluded.auto_role",[id,v?1:0]);}
  async getProfilePrivate(id:string){const r=await this.q<any>("SELECT profile_private FROM sessions WHERE discord_user_id=$1",[id]);return r[0]?.profile_private===1;} async setProfilePrivate(id:string,v:boolean){const r=await this.pool.query("UPDATE sessions SET profile_private=$1 WHERE discord_user_id=$2",[v?1:0,id]);return r.rowCount??0;}
  // 세션 행이 없으면 null(= carol을 쓴 적 없는 사용자 → 방침 변경 고지 대상 아님).
  async getPolicyAck(id:string):Promise<number|null>{const r=await this.q<any>("SELECT policy_ack FROM sessions WHERE discord_user_id=$1",[id]);return r[0]?Number(r[0].policy_ack??0):null;}
  async setPolicyAck(id:string,v:number){await this.q("INSERT INTO sessions(discord_user_id,policy_ack) VALUES($1,$2) ON CONFLICT(discord_user_id) DO UPDATE SET policy_ack=excluded.policy_ack",[id,v]);}
  async getTranslateTitles(id:string){const r=await this.q<any>("SELECT translate_titles FROM sessions WHERE discord_user_id=$1",[id]);return r[0]?.translate_titles===1;} async setTranslateTitles(id:string,v:boolean){await this.q("INSERT INTO sessions(discord_user_id,translate_titles) VALUES($1,$2) ON CONFLICT(discord_user_id) DO UPDATE SET translate_titles=excluded.translate_titles",[id,v?1:0]);}
  async getEnabledBookmarkletPresetIds(id:string){const r=await this.q<any>("SELECT preset_bookmarklets FROM sessions WHERE discord_user_id=$1",[id]);try{const x=JSON.parse(r[0]?.preset_bookmarklets??"[]");return Array.isArray(x)?x.filter((v):v is string=>typeof v==='string'):[];}catch{return [];}}
  async setBookmarkletPresetEnabled(id:string,p:string,v:boolean){const a=await this.getEnabledBookmarkletPresetIds(id),n=v?[...new Set([...a,p])]:a.filter(x=>x!==p);const r=await this.pool.query("UPDATE sessions SET preset_bookmarklets=$1 WHERE discord_user_id=$2",[JSON.stringify(n),id]);return r.rowCount??0;}
  async getExtraBookmarklets(id:string){const r=await this.q<any>("SELECT extra_bookmarklets FROM sessions WHERE discord_user_id=$1",[id]);try{return JSON.parse(r[0]?.extra_bookmarklets??"[]");}catch{return [];}} async addExtraBookmarklet(id:string,l:string,c:string){const a=(await this.getExtraBookmarklets(id)).filter((x:any)=>x.label!==l);a.push({label:l,code:c});await this.q("INSERT INTO sessions(discord_user_id,extra_bookmarklets) VALUES($1,$2) ON CONFLICT(discord_user_id) DO UPDATE SET extra_bookmarklets=excluded.extra_bookmarklets",[id,JSON.stringify(a)]);} async removeExtraBookmarklet(id:string,l:string){const a=await this.getExtraBookmarklets(id),n=a.filter((x:any)=>x.label!==l);if(n.length===a.length)return false;await this.q("UPDATE sessions SET extra_bookmarklets=$1 WHERE discord_user_id=$2",[JSON.stringify(n),id]);return true;}
  async getConstantsCache(){const r=await this.q<any>("SELECT data,updated_at AS \"updatedAt\" FROM constants_cache WHERE key='main'");return r[0]??null;} async saveConstantsCache(d:string){await this.q("INSERT INTO constants_cache VALUES('main',$1,$2) ON CONFLICT(key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at",[d,Date.now()]);}
  async getRatingCardCache(fc:string){const r=await this.q<any>("SELECT rating_card_blob AS blob,rating_card_synced_at AS \"syncedAt\",rating_card_version AS version FROM profiles WHERE friend_code=$1",[fc]);return r[0]?.blob?r[0]:null;} async saveRatingCardCache(fc:string,d:Buffer,s:number,v:number){await this.q("UPDATE profiles SET rating_card_blob=$1,rating_card_synced_at=$2,rating_card_version=$3 WHERE friend_code=$4",[d,s,v,fc]);}
  async getAllAliases(){return this.q("SELECT id,title,alias,is_translation AS \"isTranslation\" FROM song_aliases ORDER BY title,alias");} async getTranslationAliases(){return this.q("SELECT title,alias FROM song_aliases WHERE is_translation=1");} async addAlias(t:string,a:string){const r=await this.q<any>("INSERT INTO song_aliases(title,alias) VALUES($1,$2) ON CONFLICT(title,alias) DO NOTHING RETURNING id",[t,a]);return r[0]?{id:r[0].id,title:t,alias:a,isTranslation:false}:null;} async deleteAlias(id:number){const r=await this.pool.query("DELETE FROM song_aliases WHERE id=$1",[id]);return (r.rowCount??0)>0;} async setAliasTranslation(id:number,on:boolean){return this.tx(async c=>{const r=await c.query<any>("SELECT title FROM song_aliases WHERE id=$1",[id]);if(!r.rows[0])return null;if(on)await c.query("UPDATE song_aliases SET is_translation=0 WHERE title=$1",[r.rows[0].title]);await c.query("UPDATE song_aliases SET is_translation=$1 WHERE id=$2",[on?1:0,id]);return r.rows[0].title;});}
  async getMessageOverrides(){return this.q<Db.BotMessageRow>("SELECT key,text FROM bot_messages");}
  async setMessageOverride(key:string,text:string){await this.pool.query("INSERT INTO bot_messages(key,text,updated_at) VALUES($1,$2,$3) ON CONFLICT(key) DO UPDATE SET text=EXCLUDED.text, updated_at=EXCLUDED.updated_at",[key,text,Date.now()]);}
  async deleteMessageOverride(key:string){const r=await this.pool.query("DELETE FROM bot_messages WHERE key=$1",[key]);return (r.rowCount??0)>0;}
  async getRegisteredUserCount(){const r=await this.q<any>("SELECT count(*) n FROM sessions WHERE friend_code<>''");return Number(r[0]?.n??0);} async getLastSyncTime(){const r=await this.q<any>("SELECT max(last_synced_at) t FROM profiles");return r[0]?.t??null;} async getInactiveProfileFriendCodes(t:number){const r=await this.q<any>("SELECT friend_code AS \"friendCode\" FROM profiles WHERE last_synced_at<$1 AND rating_card_blob IS NOT NULL",[Date.now()-t]);return r.map((x:any)=>x.friendCode);} async clearRatingCardCacheForInactive(t:number){const r=await this.pool.query("UPDATE profiles SET rating_card_blob=NULL,rating_card_synced_at=0 WHERE last_synced_at<$1 AND rating_card_blob IS NOT NULL",[Date.now()-t]);return r.rowCount??0;}
}
export function createPostgresStorage(config:string|PoolConfig){return new PostgresStorage(config);} export async function initializePostgresStorage(config:string|PoolConfig){const s=createPostgresStorage(config);await s.initialize();return s;}
